<?php

namespace AppBundle\Repository;

/**
 * BuyerRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyerRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
