<?php

namespace AppBundle\Repository;

/**
 * ListingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingsRepository extends \Doctrine\ORM\EntityRepository
{
}
