<?php

namespace AppBundle\Repository;

/**
 * OpenOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpenOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
