<?php

namespace AppBundle\Repository;

/**
 * SellerRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellerRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
